import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full h-screen flex flex-col justify-center items-center">
        <h1 className="text-3xl font-bold text-center">Gpt3 Poet</h1>
        <div className="max-w-2xl mx-auto">
          <form className="flex flex-row gap-x-4 my-8 justify-center">
            <input
              className="px-3 py-2 text-lg rounded-lg border-2"
              type="text"
              placeholder="Subject matter"
            />
            <button
              type="submit"
              className="px-4 py-3 font-semibold rounded-lg bg-black text-white"
            >
              Submit
            </button>
          </form>
          <div className="text-lg ">
            Touching grass, it's a feeling so sublime, As I feel the blades
            running through my fingers' rhyme. This is what I love, the warmth
            of the sun, The gentle breeze, I can't help but run. Frolicking, I
            laugh while I explore, The grassy meadow, I just can't ignore. The
            softness of the ground, I can't deny, The sweetness of the air, it's
            a lullaby. The aroma, it's a scent so divine, It's like a melody, so
            sweet and sublime. The colors so vibrant, I'm in awe, A moment of
            beauty, I'm feeling no flaw. I'm glad I can feel the grass so green,
            It brings me peace, a feeling so serene. A moment of joy, I won't
            soon forget, Touching grass, it's a feeling I won't regret.
          </div>
        </div>
      </main>
    </>
  );
}
